### ISSUE TITLE
Support for TSV files

### ISSUE THREAD

**Issue by bbehrendtMRU** [jins-tkomoda/sheets-preview-x#1]
This project is exactly what I have been looking for to use with my Chromebook.    Is there any chance you would publish an update to support tab separated files (TSV)?

**Comment by bbehrendtMRU** [comment]
Update, if I drag a tsv onto the app, it will open fine, but it will not let me set sheets-preview-x as the default to open.

**Comment by tkomde** [comment]
@bbehrendtMRU Thanks for the comment. The code has been modified. The application is under review, so please wait. (You can use it as soon as you import this repository)

**Comment by bbehrendtMRU** [comment]
Wow, thank you so much.
